import { Metadata } from "next"

export const metadata: Metadata={
  title: {
    default:"tutorial",
    template:"%s | Tutorial"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      
      <body>
      <header>Header</header>
        {children}
        <footer>Footer</footer>
        </body>
      
    </html>
  )
}
